/*
 * This file is generated by jOOQ.
 */
package narrato.jooq.models;


import narrato.jooq.models.tables.ArticleFavorite;
import narrato.jooq.models.tables.ArticleTag;
import narrato.jooq.models.tables.Articles;
import narrato.jooq.models.tables.Comments;
import narrato.jooq.models.tables.Tags;
import narrato.jooq.models.tables.UserFollower;
import narrato.jooq.models.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article_favorite</code>.
     */
    public static final ArticleFavorite ARTICLE_FAVORITE = ArticleFavorite.ARTICLE_FAVORITE;

    /**
     * The table <code>public.article_tag</code>.
     */
    public static final ArticleTag ARTICLE_TAG = ArticleTag.ARTICLE_TAG;

    /**
     * The table <code>public.articles</code>.
     */
    public static final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>public.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>public.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>public.user_follower</code>.
     */
    public static final UserFollower USER_FOLLOWER = UserFollower.USER_FOLLOWER;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
